/* day6 practise */
use cdacmumbaisept2021;
show tables;
CREATE TABLE EMPLOYEE(EMPNO int,ENAME varchar(20),SALARY float,DEPTNO int, JOB char(3),MGR int);
INSERT INTO EMPLOYEE(EMPNO,ENAME,SALARY,DEPTNO,JOB,MGR)VALUES(1,'Arun',8000,1,'M',4);
INSERT INTO EMPLOYEE VALUES(2,'Aditya',7000,1,'C',1);
INSERT INTO EMPLOYEE VALUES(3,'Kirun',3000,1,'C',1);
INSERT INTO EMPLOYEE VALUES(4,'Jack',9000,2,'M',null);
INSERT INTO EMPLOYEE VALUES(5,'Thmoas',8000,2,'C',4);
SELECT * FROM EMPLOYEE;
/* GROUP BY  */
SELECT DEPTNO,SUM(SALARY)FROM EMPLOYEE GROUP BY DEPTNO;
SELECT SUM(SALARY)FROM EMPLOYEE GROUP BY DEPTNO;
SELECT DEPTNO,MIN(SALARY)FROM EMPLOYEE GROUP BY DEPTNO;
SELECT DEPTNO,MAX(SALARY)FROM employee GROUP BY DEPTNO;
SELECT COUNT(*)FROM EMPLOYEE;
SELECT DEPTNO,COUNT(*)FROM EMPLOYEE GROUP BY DEPTNO;
/* USE WHERE CLAUSE */
SELECT * FROM EMPLOYEE WHERE SALARY>7000 GROUP BY DEPTNO;
SELECT ENAME,SALARY FROM EMPLOYEE WHERE SALARY BETWEEN 4000 AND 9000;

SELECT DEPTNO,SUM(SALARY) FROM EMPLOYEE GROUP BY DEPTNO,JOB;
SELECT * FROM EMPLOYEE GROUP BY MGR;

/* GRUOPU BY NAME */
INSERT INTO EMPLOYEE VALUES(6,'JACK',1000,3,'M',NULL);
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE GROUP BY ENAME;
DELETE FROM employee WHERE EMPNO=6;
SELECT * FROM EMPLOYEE;
SELECT DEPTNO,SUM(SALARY)FROM EMPLOYEE GROUP BY DEPTNO HAVING MAX(SALARY);
SELECT MAX(SUM_SAL)FROM (SELECT SUM(SALARY) SUM_SAL FROM EMPLOYEE GROUP BY DEPTNO) AS TEMPP;
/* JOINTS */
CREATE TABLE DEPT(DEPTNO int,DNAME varchar(15),LOCATION varchar(12));
insert into DEPT values(1,'Traning','Bombay');
insert into DEPT values(2,'Exports','Delhi');
insert into DEPT values(3,'Marketing','Calcatta');
select * from DEPT;
/* Equijoin*/                /*dRIVING TABLE*/
SELECT DNAME,ENAME FROM EMPLOYEE,DEPT WHERE EMPLOYEE.DEPTNO=DEPT.DEPTNO;/* LESS ROWS IN OUTER LOOP THEN IT IS FASTER */
SELECT ENAME,DNAME FROM DEPT,EMPLOYEE WHERE DEPT.DEPTNO=EMPLOYEE.DEPTNO;
SELECT ENAME,DNAME FROM EMPLOYEE,DEPT WHERE DEPT.DEPTNO=EMPLOYEE.DEPTNO ORDER BY ENAME;
SELECT DNAME,ENAME FROM EMPLOYEE ,DEPT WHERE DEPTNO.DEPT=DEPTNO.EMPLOYEE;/* NOT WORKIONG BCOZ FIRST I WRITE COLUMN NAME.TABLENAME*/
SELECT DNAME,ENAME FROM EMPLOYEE,DEPT WHERE DEPT.DEPTNO=EMPLOYEE.DEPTNO ORDER BY 2;
SELECT * FROM DEPT,EMPLOYEE WHERE DEPT.DEPTNO=EMPLOYEE.DEPTNO;

SELECT DEPT.DEPTNO,DEPT.DNAME,DEPT.LOCATION,EMPLOYEE.EMPNO,EMPLOYEE.ENAME,EMPLOYEE.SALARY,EMPLOYEE.JOB,EMPLOYEE.MGR FROM EMPLOYEE,DEPT ORDER BY 1;

SELECT DEPT WHERE DEPT.DEPTNO=EMPLOYEE.DEPTNO GROUP BY DNAME;/* ERROR*/
SELECT DNAME, SUM(SALARY)FROM EMPLOYEE,DEPT WHERE DEPT.DEPTNO=EMPLOYEE.DEPTNO GROUP BY DNAME;
/* INEQUIJOIN */
SELECT DNAME,ENAME FROM EMPLOYEE,DEPT WHERE DEPT.DEPTNO !=EMPLOYEE.DEPTNO; 

/* Outer join */
/* Right Outer join */
SELECT DNAME,ENAME FROM EMPLOYEE LEFT OUTER JOIN DEPT ON (DEPT.DEPTNO=EMPLOYEE.DEPTNO);
SELECT DNAME,ENAME FROM EMPLOYEE RIGHT OUTER JOIN DEPT ON (DEPT.DEPTNO=EMPLOYEE.DEPTNO);

SELECT DNAME,ENAME FROM EMPLOYEE LEFT OUTER JOIN DEPT ON(DEPT.DEPTNO=EMPLOYEE.DEPTNO)
                            UNION
SELECT DNAME,ENAME FROM EMPLOYEE RIGHT OUTER JOIN DEPT ON(DEPT.DEPTNO=EMPLOYEE.DEPTNO);
SELECT DNAME,ENAME FROM EMPLOYEE RIGHT OUTER















SELECT DEPT.DEPTNO,DEPT.DNAME,DEPT.LOCATION,EMPLOYEE.EMPNO,EMPLOYEE.ENAME,EMPLOYEE.SALARY,EMPLOYEE.JOB,EMPLOYEE.MGR WHERE DEPT.DEPTNO=EMPLOYEE.DEPT
